### ISSUE TITLE
ui.bootstrap Modal 

### ISSUE THREAD

**Issue by openainext** [danicomas/angular-jquery-validate#3] opened 2014-11-05 03:37 UTC
$scope.eventformvalidateapi  null

**Comment by danicomas** [comment] 2014-11-05 08:51
Attach your example, here or a jsFiddle thanks

**Comment by openainext** [comment] 2014-11-05 09:42
Find the problem  3q

**Comment by danicomas** [comment] 2014-11-05 09:48
Can you close this issue If the problem is solved? Thanks!

**Closed as completed** 2014-11-05 09:49 UTC

**Comment by saniokazzz** [comment] 2016-02-18 20:47
@wanglong167 how have you solved the issue?
